spring:
  cloud:
    gateway:
      routes:
        - id: terminal-service
          uri: lb://TERMINAL-SERVICE
          predicates:
            - Path=/terminals/**
          filters:
            -name: AuthenticationFilter
            args:
              roles:[admin,teamLeader,operator]

        - id: defect-listing-service
          uri: lb://DEFECT-LISTING-SERVICE
          predicates:
            - Path=/defectListing/**
          filters:
            - AuthenticationFilter=teamLeader

        - id: defect-save-service
          uri: lb://DEFECT-SAVE-SERVICE
          predicates:
            - Path=/defects/**,/vehicle/**
          filters:
            - AuthenticationFilter=operator

        - id: user-management-service
          uri: lb://USER-MANAGEMENT-SERVICE
          predicates:
            - Path=/users/**,/roles/**
          filters:
            - AuthenticationFilter=admin

        - id: security-service
          uri: lb://SECURITY-SERVICE
          predicates:
            - Path=/auth/**
  application:
    name: gateway
server:
  port: 8888

logging:
  config: classpath:log4j2.xml
