spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: :defect-save-service
          uri: lb://defect-save-service
          predicates:
            - Path=/defects/**
        - id: defect-listing-service
          uri: lb://defect-listing-service
          predicates:
            -  Path=/defectListing/**
        - id: user-management-service
          uri: lb://user-management-service
          predicates:
            - Path=/users/**
        - id: terminal-service
          uri: lb://terminal-service
          predicates:
            - Path=/terminals/**
server:
  port: 8888


eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
